title: "fangzuzong blog"
author: "inglix11"
url: "http://fangzuzong.com"
email: "inglix11@gmail.com"
description: "fangzuzong blog"

auto: false
source: .
paginate: 10
paginate_files:
 - index.html

markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
