title: "smallfish blog"
url: "www.fangzuzong.com"
author: "smallfish"
email: "smallfish@gmail.com"
description: "smallfish blog"

auto: false
source: .
paginate: 10
paginate_files:
 - index.html


markdown: rdiscount
pygments: true

exclude:
  - README.markdown
  - _drafts
